# Flutter build
variables:
  projectDirectory: 'covid_19_tracker'
trigger:
- master
jobs:
  - job: Android
    pool:
      vmImage: 'macOS-latest'
    steps:
    - task: FlutterInstall@0
      inputs:
        channel: 'stable'
        version: 'latest'
    
    - task: FlutterBuild@0
      inputs:
        target: apk
        projectDirectory: $(projectDirectory)
    # - task: AndroidSigning@3
    #   inputs:
    #     apkFiles: '**/*.apk'
    #     apksign: false
    
    - task: DownloadSecureFile@1
      name: key
      displayName: Download signing key
      inputs:
        secureFile: 'key.jks'

    - task: AndroidSigning@3
      displayName: 'Signing and aligning APK file(s) **/*.apk'
      inputs:
        apkFiles: '**/*.apk'
        apksignerKeystoreFile: 'key.jks'
        apksignerKeystorePassword: '$(keypassword)'
        apksignerKeystoreAlias: '$(key)'
        apksignerKeyPassword: '$(keypassword)'
    - task: CopyFiles@2
      inputs:
        contents: '**/*.apk'
        targetFolder: '$(build.artifactStagingDirectory)'
    - task: PublishBuildArtifacts@1