# Flutter build
variables:
  projectDirectory: 'covid_19_tracker'
  name: $(BuildID)
trigger:
- master
jobs:
  - job: Android
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DownloadSecureFile@1
      name: key
      displayName: Download signing key
      inputs:
        secureFile: 'key.jks'
        
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          sudo apt-get install fastjar
          wget https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.22.1-stable.tar.xz
          sudo tar -xf ./flutter_linux_3.22.1-stable.tar.xz  -C /usr/bin/
          sudo echo $SHELL
          sudo echo $0
          sudo echo 'export PATH="$HOME/development/flutter/bin:$PATH"' >> ~/.bash_profile
          
    # - task: FlutterInstall@0
    #   displayName: "Install Flutter SDK"
    #   inputs:
    #     channel: 'stable'
    #     version: 'latest'

    - task: FlutterCommand@0
      displayName: "Run Flutter diagnostics"
      inputs:
        projectDirectory: '$(projectDirectory)'
        arguments: 'doctor -v'
    
    - task: FlutterBuild@0
      inputs:
        target: 'apk'
        projectDirectory: '$(projectDirectory)'
        buildNumber: '$(Build.BuildId)'
        
    - task: FlutterTest@0
      displayName: "Run unit tests"
      inputs:
        projectDirectory: '$(projectDirectory)'
        testName: 'coverage_test'
        
    - task: AndroidSigning@3
      displayName: 'Signing and aligning APK file(s) **/*.apk'
      inputs:
        apkFiles: '**/*.apk'
        apksignerKeystoreFile: 'key.jks'
        apksignerKeystorePassword: '$(keypassword)'
        apksignerKeystoreAlias: '$(key)'
        apksignerKeyPassword: '$(keypassword)'
        
    - task: CopyFiles@2
      inputs:
        contents: '**/*.apk'
        targetFolder: '$(build.artifactStagingDirectory)'
        
    - task: PublishBuildArtifacts@1
